### ISSUE TITLE
Bug when change not stream prop on a reactive class

### ISSUE THREAD

**Issue by xialvjun** [theadam/react-flyd-class#2]
see [webpackbin](http://www.webpackbin.com/EkLI2jgDb)

or

```
const Span = reactive('span');

const plusClick$ = stream();
const minusClick$ = stream();

const action$ = merge(
  plusClick$.map(() => 1),
  minusClick$.map(() => -1)
);

const count$ = scan((x, y) => x + y, 0, action$);


class Counter extends React.Component {
  constructor(props){
    super(props)
    this.state = {normal_state: false}
  }

  render() {
    return (
      <div>
        <div>
          <button id="plus" onClick={ (e) => plusClick$(e) }>+</button>
          <button id="minus" onClick={ (e) => minusClick$(e) }>-</button>
        </div>
        <div>
          Count: <Span style={{color: this.state.normal_state?'red':'blue'}}>{ count$ }</Span>
          <button onClick={e=>this.setState({normal_state: !this.state.normal_state})}>toggle_normal_state</button>
        </div>
      </div>
    )
  }
}
```

 click the `toggle_normal_state` button won't change the reactive span's color. 
The problem is normal state shouldn't be fixed in constructor...

```
constructor(props) {
      super(props);
      this.displayName = `FlydReactiveElement-${tag}`;
      this.state = pickProps(props, (key, value) => !isStream(value));
      this.state.mount = true;
    }
```

I'll make a PR tomorrow...or yourself fix it.

**Comment by xialvjun** [comment]
What's the use of this.state.mount...

**Comment by theadam** [comment]
Let me know if this clears it up: https://github.com/theadam/react-flyd-class#mountunmount-reactive-component

**Comment by xialvjun** [comment]
I see. But I think there is a cleaner way to do it.

```
{text$.map(text => text.length ? <span>{text}</span> : null)}
```

Well, there is a problem...

If we create the Element at the time `text$().length>0`, then it will be thought as a `self control element`, and after `text$('')` will make the self control element return a `null`. But that doesn't matter, since return null in a `render` method doesn't make React complain about, you can have a try.

If we create the Element at the time `text$().length===0`, then it will be thought as a `parent control element`, that will consume the CPU a little more. Other than that, there is no any other difference since `parent control element` is totally compatitable of `self control element`..

......(◎﹏◎)!

Well, you are talking about `react-flyd-class` rather than `react-flyd`.

So if a user want to control the element's mount status himself, then why not:

```
let A = reactive()
<A>{text$.map(text => text.length ? <span>{text}</span> : null)}</A>
```

This is manually make it a `self control element`.
This way is cleaner.

**Comment by theadam** [comment]
"Self control" elements are not a part of the API currently.  They do not allow for multiple children, and thus are not compatible with react components.  That being said, in order to control the `mount` state of parent control elements in the current form of the API, `mount` is necessary.

And actually, based on the current state of the PR regarding self-control components, it appears that a null child will cause `React.cloneElement` to be called with `null` as the first argument.  With my quick test, this will cause an error.

**Comment by xialvjun** [comment]
En....  Infact, I got "self control" idea from you... The first time I saw you Counter example, I just though the text count is controlled by the parent element 'div'...eh, the first time I saw it is in react-flyd rather than react-flyd-class....

**Comment by theadam** [comment]
By "Self control"  component, I was referring to  The proposed change to `reactive` to accept a `null` tag. Regardless, neither of these changes are  related to this bug.  If you would like to discuss other changes to the API  please open another issue.
